/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void sliderX_change(GSlider source, GEvent event) { //_CODE_:sliderX:794724:
  println("slider1 - GSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:sliderX:794724:

public void sliderY_change(GSlider source, GEvent event) { //_CODE_:sliderY:478817:
  println("slider2 - GSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:sliderY:478817:

public void sliderZ_change(GSlider source, GEvent event) { //_CODE_:sliderZ:263559:
  println("slider3 - GSlider event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:sliderZ:263559:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  sliderX = new GSlider(this, 50, 34, 255, 40, 10.0);
  sliderX.setLimits(0.5, 0.0, 1.0);
  sliderX.setNumberFormat(G4P.DECIMAL, 2);
  sliderX.setLocalColorScheme(GCScheme.RED_SCHEME);
  sliderX.setOpaque(false);
  sliderX.addEventHandler(this, "sliderX_change");
  sliderY = new GSlider(this, 53, 88, 255, 40, 10.0);
  sliderY.setLimits(0.5, 0.0, 1.0);
  sliderY.setNumberFormat(G4P.DECIMAL, 2);
  sliderY.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  sliderY.setOpaque(false);
  sliderY.addEventHandler(this, "sliderY_change");
  sliderZ = new GSlider(this, 53, 136, 255, 40, 10.0);
  sliderZ.setLimits(0.5, 0.0, 1.0);
  sliderZ.setNumberFormat(G4P.DECIMAL, 2);
  sliderZ.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  sliderZ.setOpaque(false);
  sliderZ.addEventHandler(this, "sliderZ_change");
}

// Variable declarations 
// autogenerated do not edit
GSlider sliderX; 
GSlider sliderY; 
GSlider sliderZ; 

